PUT http://localhost:3001/api/posts/64db3557be41f20bbc191f27/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QxIiwiaWQiOiI2NGNmNGI3YjZlZTc4NWI5NDkwNDQ4MzEiLCJpYXQiOjE2OTIwODc1ODQsImV4cCI6MTY5MjA5MTE4NH0.ZrcChLqd5P67aRddUEh6Q90uOtJOxPxizI5EzTg4fOY

{
	"title": "changedtitle"
}